// Competition config (SPEC 8.3): defaults, ranges and the SAME parameter counting as the backend
// (backend/app/chess_net/config.py). Defaults/tiers come from shared/config_defaults.json (generated by the backend).
import shared from "../../../shared/config_defaults.json";

export type Json = Record<string, unknown>;
export interface Tier { name: string; max_params: number; search_depth_full_moves: number }

export const DEFAULTS = shared.defaults as unknown as Config;
export const TIERS = shared.tiers as Tier[];
export const MAX_PARAMS = shared.max_params;
export const ACTIVATION_NAMES = shared.activations as string[];
export const RANGES = shared.ranges as Record<string, { minimum?: number; maximum?: number }>;

export interface Config {
  layers: number; width: number; layer_widths: number[] | null;
  activation: { name: string; alpha: number; beta: number; cap: number };
  loss: { name: "mse" | "huber" | "bce" | "l1"; delta: number };
  lr: number; batch_size: number; optimizer: "sgd" | "momentum" | "adam";
  target_type: "winprob" | "cp"; eval_squash_scale: number; mate_clip: number;
  input_extras: { stm_castle: boolean; en_passant: boolean; material: boolean; attacks: boolean };
  perspective_flip: boolean; color_flip_augmentation: boolean;
  data_slice: "all" | "endgame" | "balanced" | "decisive"; sampling: "uniform" | "weighted";
  init: "xavier" | "he" | "small_normal"; lr_schedule: "constant" | "cosine" | "linear"; warmup_frac: number; grad_clip: number;
  ema: { enabled: boolean; decay: number }; normalization: "none" | "layernorm"; residual: boolean;
  output_head: "linear" | "tanh" | "sigmoid"; seed: number;
}

export const defaultConfig = (): Config => JSON.parse(JSON.stringify(DEFAULTS));

export function featureDim(e: Config["input_extras"]): number {
  return 768 + (e.stm_castle ? 5 : 0) + (e.en_passant ? 8 : 0) + (e.material ? 10 : 0) + (e.attacks ? 128 : 0);
}

export function widthsOf(c: Pick<Config, "layers" | "width" | "layer_widths">): number[] {
  return c.layer_widths && c.layer_widths.length ? c.layer_widths : Array.from({ length: c.layers }, () => c.width);
}

export function countParams(inDim: number, widths: number[], norm = "none"): number {
  let total = 0, prev = inDim;
  for (const w of widths) { total += prev * w + w + (norm === "layernorm" ? 2 * w : 0); prev = w; }
  return total + prev + 1;
}

export function tierFor(params: number): Tier {
  return TIERS.find((t) => params <= t.max_params) ?? TIERS[TIERS.length - 1];
}

export interface LocalPreview { paramCount: number; tier: Tier; errors: string[]; flopsPerSample: number }

/** Instant client-side preview (works offline); the server's /preview is authoritative. */
export function previewLocal(c: Config): LocalPreview {
  const widths = widthsOf(c);
  const inDim = featureDim(c.input_extras);
  const n = countParams(inDim, widths, c.normalization);
  const errors: string[] = [];
  if (n > MAX_PARAMS) errors.push(`too many parameters: ${n.toLocaleString()} (the limit is ${MAX_PARAMS.toLocaleString()})`);
  if (c.loss.name === "bce" && c.target_type !== "winprob") errors.push("loss 'bce' needs target_type 'winprob'");
  let prev = inDim, mm = 0;
  for (const w of widths) { mm += prev * w; prev = w; }
  return { paramCount: n, tier: tierFor(n), errors, flopsPerSample: 6 * (mm + prev) };
}
